import type { Metadata } from 'next'
import { FC, ReactNode } from 'react'
import { RootTemplateLayout } from '@/application/layout/RootTemplateLayout'
import '../application/styles/globals.sass'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

type Props = {
    children: ReactNode
}


const RootLayout: FC<Props> = (props) => {

    const { children } = props

    return (
        <RootTemplateLayout>
            {children}
        </RootTemplateLayout>
    )
}

export default RootLayout